#!/usr/bin/env python3
"""
Build all README variations from a single content source.

Usage:
    python3 build.py             # writes to ../variations/
    python3 build.py --out DIR   # writes to DIR

Edit content.py. Run this. Commit the output. The content is the source of
truth; each theme is just a skin.
"""

import argparse
import os
import sys
from urllib.parse import quote

from content import CONTENT as C


# ---------- URL helpers (all the SVG services) ---------------------------

def capsule(**params):
    base = "https://capsule-render.vercel.app/api"
    q = "&".join(f"{k}={quote(str(v), safe='')}" for k, v in params.items())
    return f"{base}?{q}"


def typing(lines, **params):
    # readme-typing-svg.demolab.com
    params.setdefault("font", "Fira+Code")
    params["lines"] = ";".join(lines)
    base = "https://readme-typing-svg.demolab.com"
    q = "&".join(f"{k}={quote(str(v), safe='+;,')}" for k, v in params.items())
    return f"{base}?{q}"


def shield(label, color, logo=None, logo_color=None, style="for-the-badge"):
    # img.shields.io static badge
    s = f"https://img.shields.io/badge/{quote(label)}-{color}?style={style}"
    if logo:
        s += f"&logo={logo}"
    if logo_color:
        s += f"&logoColor={logo_color}"
    return s


def skillicons(theme="dark", perline=13, icons=None):
    icons = icons or C["skillicons_slug"]
    return f"https://skillicons.dev/icons?i={icons}&theme={theme}&perline={perline}"


# ---------- Render: V5 — TERMINAL / PHOSPHOR (user's favorite) -----------

def render_v5():
    header = capsule(
        type="soft", color="0:0a1f0f,100:112a17",
        height=180, section="header",
        text="tyron samaroo", fontSize=48, fontColor="7aff9e",
        fontAlignY=38, desc="ml × systems · nyc",
        descAlignY=62, descSize=16, animation="fadeIn",
    )
    boot = typing(
        C["boot_lines"],
        size=16, weight=500, color="7aff9e",
        background="0a1f0f00", center="true", vCenter="true",
        width=720, height=150, duration=2800, pause=400,
    )
    tags = typing(
        C["rotating_taglines"],
        size=20, weight=600, color="b4f2c4",
        background="0a1f0f00", center="true", vCenter="true",
        width=600, height=50, duration=3500, pause=800,
    )
    badges = " ".join([
        f"[![Portfolio](https://img.shields.io/badge/portfolio-{C['portfolio'].replace('.','%2E')}-7aff9e?style=for-the-badge&logo=vercel&logoColor=black&labelColor=0a1f0f)](https://{C['portfolio']})",
        f"[![Email](https://img.shields.io/badge/email-{C['email'].replace('@','%40').replace('.','%2E')}-7aff9e?style=for-the-badge&logo=gmail&logoColor=black&labelColor=0a1f0f)](mailto:{C['email']})",
        f"[![LinkedIn](https://img.shields.io/badge/linkedin-{C['handle']}-7aff9e?style=for-the-badge&logo=linkedin&logoColor=black&labelColor=0a1f0f)]({C['linkedin_url']})",
    ])
    stack_badges = " ".join(
        f"![{s['name']}](https://img.shields.io/badge/{quote(s['name'], safe='')}-{s['color']}?style=for-the-badge&logo={s['logo']}&logoColor={s['text']})"
        for s in C["stack"]
    )
    # Projects 2x3 table
    p = C["projects"]
    def cell(pr):
        tags = " · ".join(pr["tags"])
        return (f"<b><a href=\"{pr['url']}\">{pr['emoji']} {pr['name']}</a></b><br/>"
                f"<sub>{pr['short']}</sub><br/><sub><i>{pr['insight']}</i></sub><br/>"
                f"<sub><code>{tags}</code></sub>")
    rows = []
    for i in range(0, 6, 2):
        rows.append(f"| {cell(p[i])} | {cell(p[i+1])} |")
    projects_tbl = "| | |\n|---|---|\n" + "\n".join(rows)
    focus = "\n".join(f"  › {line}" for line in C["now_lines"])
    footer = capsule(
        type="soft", color="0:112a17,100:0a1f0f",
        height=80, section="footer",
    )
    return TEMPLATE_V5.format(
        header=header, boot=boot, tags=tags, badges=badges,
        whoami_name=C["name"], whoami_role=C["short_role"],
        whoami_bio=C["bio_short"], whoami_mantra=C["mantra"],
        stack_badges=stack_badges, projects_tbl=projects_tbl,
        focus=focus, footer=footer, quote=C["quote"],
    )


TEMPLATE_V5 = """<!-- generated by .build/build.py — edit content.py, not this file -->
<div align="center">

<a href="#"><img src="{header}" width="100%" alt="header"/></a>

<a href="#"><img src="{boot}" alt="boot sequence"/></a>

<a href="#"><img src="{tags}" alt="rotating taglines"/></a>

{badges}

</div>

---

```js
$ whoami

const tyron = {{
  name:    "{whoami_name}",
  role:    "{whoami_role}",
  bio:     "{whoami_bio}",
  mantra:  "{whoami_mantra}",
}};
```

### `$ cat ~/arsenal.log`

<div align="center">

{stack_badges}

</div>

### `$ ls -la ~/projects`

{projects_tbl}

### `$ cat ~/focus.txt`

```text
{focus}
```

<div align="center">

![STATUS](https://img.shields.io/badge/STATUS-shipping%20daily-7aff9e?style=for-the-badge&labelColor=0a1f0f)
![OPEN TO](https://img.shields.io/badge/OPEN%20TO-collabs%20%26%20roles-7aff9e?style=for-the-badge&labelColor=0a1f0f)
![LOCATION](https://img.shields.io/badge/LOCATION-NYC-7aff9e?style=for-the-badge&labelColor=0a1f0f)

<sub><i>"{quote}"</i></sub>

<img src="{footer}" width="100%" alt="footer"/>

</div>
"""


# ---------- Render: V1 — CRT TERMINAL -----------------------------------

def render_v1():
    header = capsule(
        type="waving", color="0:00ff88,100:003b1c",
        height=160, section="header",
        text="// tyron.samaroo", fontSize=40, fontColor="00ff88",
        animation="fadeIn",
    )
    boot = typing(
        ["> booting tyron.os ...", "> loaded: ml.modules", "> loaded: compiler.modules",
         "> status: READY"],
        size=18, weight=600, color="00ff88", background="00000000",
        center="true", vCenter="true", width=720, height=90, duration=2800, pause=400,
    )
    icons = skillicons(theme="dark", perline=13)
    return f"""<!-- generated — edit content.py -->
<div align="center">

<img src="{header}" width="100%" alt="header"/>

<img src="{boot}" alt="boot"/>

### `> whoami`

```
> {C['name']}
> {C['short_role']}
> {C['bio_short']}
```

### `> stack --list`

<img src="{icons}" alt="stack"/>

### `> ls ~/projects`

""" + "\n".join(
        f"- **[{p['emoji']} {p['name']}]({p['url']})** — {p['short']}"
        for p in C["projects"]
    ) + f"""

### `> cat now.txt`

```
""" + "\n".join(f"~ {l}" for l in C["now_lines"]) + f"""
```

<sub>"{C['quote']}"</sub>

</div>
"""


# ---------- Render: V2 — CYBERPUNK DUOTONE ------------------------------

def render_v2():
    header = capsule(
        type="waving", color="0:ff2a9d,100:00f0ff",
        height=180, section="header",
        text="TYRON//SAMAROO", fontSize=44, fontColor="ffffff",
        animation="twinkling",
    )
    tag = typing(
        ["> jack into the grid ...", "> ml × systems × vibes"],
        size=20, weight=700, color="ff2a9d", background="0a0014",
        center="true", vCenter="true", width=720, height=70, duration=3000, pause=600,
    )
    badges = " ".join([
        f"[![mail](https://img.shields.io/badge/mail-ff2a9d?style=for-the-badge&logo=gmail&logoColor=white)](mailto:{C['email']})",
        f"[![li](https://img.shields.io/badge/linkedin-00f0ff?style=for-the-badge&logo=linkedin&logoColor=white)]({C['linkedin_url']})",
        f"[![web](https://img.shields.io/badge/{C['portfolio'].replace('.','%2E')}-ff2a9d?style=for-the-badge&logo=vercel&logoColor=white)](https://{C['portfolio']})",
    ])
    # stack bars
    bars = []
    for s in C["stack"][:8]:
        dots = "━" * 16
        bars.append(f"`{s['name']:<11}` {dots}  `// {s['logo']}`")
    stack_block = "\n".join(bars)
    p = C["projects"]
    def card(pr):
        return (f"▸ **[{pr['name']}]({pr['url']})** {pr['emoji']}  \n"
                f"  `{pr['short']}`  \n"
                f"  <sub><i>{pr['insight']}</i></sub>")
    proj_block = "\n\n".join(card(pr) for pr in p)
    return f"""<!-- generated — edit content.py -->
<div align="center">

<img src="{header}" width="100%" alt="header"/>

<img src="{tag}" alt="tag"/>

{badges}

</div>

## `// > BIOS`

```
{C['name']} · {C['short_role']}
{C['bio_short']}
mantra // {C['mantra']}
```

## `// > STACK`

```
{stack_block}
```

## `// > BUILDS`

{proj_block}

## `// > NOW`

""" + "\n".join(f"- {l}" for l in C["now_lines"]) + f"""

<sub>`// "{C['quote']}"`</sub>
"""


# ---------- Render: V3 — BRUTALIST PRINT --------------------------------

def render_v3():
    stack_list = "  ·  ".join(s["name"] for s in C["stack"])
    projects_md = "\n\n".join(
        f"**§ {i+1:02d}** &nbsp; [{p['name']}]({p['url']})  \n"
        f"{p['short']}  \n"
        f"<sub>{p['insight']}</sub>"
        for i, p in enumerate(C["projects"])
    )
    return f"""<!-- generated — edit content.py -->

# TYRON SAMAROO

**ISSUE №001 · README.MD · REV. 2026 · PRINTED IN BROOKLYN**

---

## § 1 &nbsp; WHOAMI

{C['bio_short']}

> {C['mantra']}

---

## § 2 &nbsp; ARSENAL

`{stack_list}`

---

## § 3 &nbsp; THINGS BUILT

{projects_md}

---

## § 4 &nbsp; NOW

""" + "\n".join(f"- {l}" for l in C["now_lines"]) + f"""

---

**CONTACT** &nbsp; [{C['email']}](mailto:{C['email']}) · [{C['portfolio']}](https://{C['portfolio']}) · [linkedin{C['linkedin_path']}]({C['linkedin_url']})

<sub><i>"{C['quote']}"</i></sub>
"""


# ---------- Render: V4 — AMBER BBS --------------------------------------

def render_v4():
    header = capsule(
        type="soft", color="0:1a0f00,100:3d2400",
        height=160, section="header",
        text="▓▓ TYRON BBS ▓▓",
        fontSize=36, fontColor="ffb000",
        desc="node:01 · 2400 baud · sysop: tyron",
        descAlignY=62, descSize=14,
    )
    icons = skillicons(theme="dark", perline=13)
    proj_lines = "\n".join(
        f"  [{chr(65+i)}] {p['name']:<24} {p['short']}"
        for i, p in enumerate(C["projects"])
    )
    return f"""<!-- generated — edit content.py -->

<div align="center">

<img src="{header}" width="100%" alt="header"/>

</div>

```
╔══════════════════════════════════════════════════════════════════════╗
║                                                                      ║
║   WELCOME TO TYRON BBS ▓▓▓                                           ║
║   {C['short_role']:<66} ║
║                                                                      ║
║   [M]AIN MENU       [F]ILE AREA       [D]OOR GAMES       [Q]UIT      ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
```

## `[M] >> SYSOP BIO`

{C['bio_short']}

> *{C['mantra']}*

## `[F] >> FILE AREA`

```
{proj_lines}
```

## `[D] >> STACK (loaded modules)`

<div align="center">
<img src="{icons}" alt="stack"/>
</div>

## `[?] >> CONTACT`

```
  mail ....... {C['email']}
  www ........ https://{C['portfolio']}
  linkedin ... {C['linkedin_url']}
```

<sub>`// "{C['quote']}"`</sub>
"""


# ---------- Render: V6 — RESEARCH NOTEBOOK ------------------------------

def render_v6():
    threads = [
        ("ASL data vs architecture",
         "Curation beat every model change I made. Is that data or me?"),
        ("Minimum viable compiler",
         "How small can a real Java compiler get before the design collapses?"),
        ("Zero-deps as a discipline",
         "What do you learn building HTTP from the JDK that libraries hide from you?"),
        ("LLMs vs classical IR",
         "Where does BM25 still beat embeddings? Explainability, mostly."),
    ]
    threads_md = "\n\n".join(f"> **{t}**  \n> {q}" for t, q in threads)
    exp_md = "\n\n".join(
        f"**Experiment {i+1}** — [{p['name']}]({p['url']})  \n"
        f"_{p['short']}_  \n"
        f"**Finding.** {p['insight']}"
        for i, p in enumerate(C["projects"])
    )
    return f"""<!-- generated — edit content.py -->

# {C['name']}

_{C['short_role']}_

{C['bio_short']}

---

## Current threads

{threads_md}

---

## Experiments

{exp_md}

---

## On my desk

- _Designing Data-Intensive Applications_ — Kleppmann
- _Compilers: Principles, Techniques, and Tools_ — Aho/Sethi/Ullman
- _The Practice of Programming_ — Kernighan/Pike

---

**Elsewhere.** [{C['portfolio']}](https://{C['portfolio']}) · [{C['email']}](mailto:{C['email']}) · [linkedin{C['linkedin_path']}]({C['linkedin_url']})

<sub><i>"{C['quote']}"</i></sub>
"""


# ---------- Render: VA — MINIMAL ----------------------------------------

def render_vA():
    chips = " ".join(
        f"![{s['name']}](https://img.shields.io/badge/{quote(s['name'], safe='')}-eee?style=flat-square&logo={s['logo']}&logoColor=555)"
        for s in C["stack"][:8]
    )
    # 3 selected projects for minimal view
    sel = [C["projects"][0], C["projects"][1], C["projects"][3]]
    proj_md = "\n\n".join(
        f"**[{p['name']}]({p['url']})** — {p['short']} _{p['insight']}_"
        for p in sel
    )
    return f"""<!-- generated — edit content.py -->

### Hi, I'm {C['name']}.

{C['bio_short']}

{chips}

---

{proj_md}

---

**Currently.** {C['now_lines'][0]}.

**Contact.** [{C['email']}](mailto:{C['email']}) · [{C['portfolio']}](https://{C['portfolio']}) · [linkedin]({C['linkedin_url']})
"""


# ---------- Render: VC — DEMO REEL --------------------------------------

def render_vC():
    p = C["projects"]
    def tile(pr, i):
        slug = pr["name"].lower().replace("_", "-").replace(" ", "-")
        return (f"<td align=\"center\" width=\"33%\">"
                f"<img src=\"./assets/{slug}.gif\" width=\"260\" alt=\"{pr['name']}\"/><br/>"
                f"<b><a href=\"{pr['url']}\">{pr['emoji']} {pr['name']}</a></b><br/>"
                f"<sub>{pr['short']}</sub>"
                f"</td>")
    rows = []
    for i in range(0, 6, 3):
        rows.append("<tr>" + "".join(tile(p[i+j], i+j) for j in range(3)) + "</tr>")
    grid = "<table>\n" + "\n".join(rows) + "\n</table>"
    chips = " ".join(
        f"![{s['name']}](https://img.shields.io/badge/{quote(s['name'], safe='')}-{s['color']}?style=flat&logo={s['logo']}&logoColor={s['text']})"
        for s in C["stack"][:8]
    )
    return f"""<!-- generated — edit content.py -->

<div align="center">

# {C['name']}

**{C['short_role']}**

{C['bio_short']}

</div>

---

<div align="center">

{grid}

</div>

---

<div align="center">

{chips}

**Now.** {C['now_lines'][0]}. &nbsp; **Contact.** [{C['email']}](mailto:{C['email']})

</div>
"""


# ---------- Render: V7 — DEV DASHBOARD (matches tyronsamaroo.dev) -------

def render_v7():
    # zinc-950 #09090b + violet-500 #8b5cf6 + blue-500 #3b82f6, JetBrains Mono
    header = capsule(
        type="soft", color="0:09090b,50:1a1033,100:09090b",
        height=240, section="header",
        text="Tyron Samaroo", fontSize=60, fontColor="a78bfa",
        fontAlignY=40, desc="dev dashboard · ml × systems · nyc",
        descAlignY=62, descSize=16, animation="fadeIn",
        fontFamily="JetBrains Mono",
    )
    # Gradient accent bar under header (thin violet→blue strip)
    accent = capsule(
        type="rect", color="0:8b5cf6,50:6366f1,100:3b82f6",
        height=3, section="header",
    )
    tagline = typing(
        ["⌘K to explore",
         "STATUS: ● online",
         "building at the seam of ML × systems",
         "ship it. then make it weird."],
        font="JetBrains+Mono", size=18, weight=500,
        color="a78bfa", background="09090b00",
        center="true", vCenter="true",
        width=720, height=54, duration=3500, pause=700,
    )
    # Dashboard-style "cards" row: badges styled as site chips
    nav = " ".join([
        f"[![portfolio](https://img.shields.io/badge/portfolio-{C['portfolio'].replace('.','%2E')}-8b5cf6?style=for-the-badge&logo=vercel&logoColor=white&labelColor=09090b)](https://{C['portfolio']})",
        f"[![email](https://img.shields.io/badge/email-{C['email'].replace('@','%40').replace('.','%2E')}-3b82f6?style=for-the-badge&logo=gmail&logoColor=white&labelColor=09090b)](mailto:{C['email']})",
        f"[![linkedin](https://img.shields.io/badge/linkedin-{C['handle']}-6366f1?style=for-the-badge&logo=linkedin&logoColor=white&labelColor=09090b)]({C['linkedin_url']})",
    ])
    # PRIMARY stack — big, brand-colored, pops (Python/TS/React)
    primary_chips = " ".join(
        f"![{s['name']}](https://img.shields.io/badge/{quote(s['name'], safe='')}-{s['color']}?style=for-the-badge&logo={s['logo']}&logoColor={s['text']}&labelColor={s['color']})"
        for s in C["primary_stack"]
    )
    # Full arsenal — each tech in its native brand color so they don't blur together
    stack_chips = " ".join(
        f"![{s['name']}](https://img.shields.io/badge/{quote(s['name'], safe='')}-{s['color']}?style=for-the-badge&logo={s['logo']}&logoColor={s['text']})"
        for s in C["stack"]
    )
    # Projects as "cards" — 2×3 table, violet borders via sub labels
    p = C["projects"]
    def card(pr):
        tags = " · ".join(pr["tags"])
        return (f"<b><a href=\"{pr['url']}\">{pr['emoji']} {pr['name']}</a></b><br/>"
                f"<sub>{pr['short']}</sub><br/>"
                f"<sub><i>↳ {pr['insight']}</i></sub><br/>"
                f"<sub><code>{tags}</code></sub>")
    rows = []
    for i in range(0, 6, 2):
        rows.append(f"| {card(p[i])} | {card(p[i+1])} |")
    projects_tbl = "| | |\n|:---|:---|\n" + "\n".join(rows)
    now_md = "\n".join(f"- {l}" for l in C["now_lines"])
    footer = capsule(
        type="soft", color="0:1a1033,50:09090b,100:1a1033",
        height=80, section="footer",
    )
    return f"""<!-- generated by .build/build.py — edit content.py, not this file -->
<!-- V7 DASHBOARD — mirrors tyronsamaroo.dev palette & metaphor -->
<div align="center">

<img src="{header}" width="100%" alt="header"/>

<img src="{tagline}" alt="tagline"/>

{nav}

![STATUS](https://img.shields.io/badge/STATUS-%E2%97%8F%20online-34d399?style=for-the-badge&labelColor=09090b)
![UPTIME](https://img.shields.io/badge/UPTIME-shipping%20daily-60a5fa?style=for-the-badge&labelColor=09090b)
![REGION](https://img.shields.io/badge/REGION-NYC-a78bfa?style=for-the-badge&labelColor=09090b)

</div>

---

## `/about`

{C['bio_short']}

> *{C['mantra']}*

## `/skills`

<div align="center">

**primary** — shipping daily

{primary_chips}

<br/>

**arsenal** — proven in production

{stack_chips}

</div>

## `/projects`

{projects_tbl}

## `/now`

{now_md}

---

<div align="center">

<sub><i>"{C['quote']}"</i></sub>

<img src="{footer}" width="100%" alt="footer"/>

</div>
"""


# ---------- Main --------------------------------------------------------

THEMES = {
    "V1_terminal.md":  render_v1,
    "V2_cyberpunk.md": render_v2,
    "V3_brutalist.md": render_v3,
    "V4_retrobbs.md":  render_v4,
    "V5_github.md":    render_v5,
    "V6_notebook.md":  render_v6,
    "V7_dashboard.md": render_v7,
    "VA_minimal.md":   render_vA,
    "VC_demoreel.md":  render_vC,
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "variations"))
    args = ap.parse_args()
    out = os.path.abspath(args.out)
    os.makedirs(out, exist_ok=True)
    for fname, fn in THEMES.items():
        path = os.path.join(out, fname)
        with open(path, "w") as f:
            f.write(fn())
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
