# Single source of truth for all README variations.
# Edit me, run `python3 build.py`, commit.

CONTENT = {
    "name": "Tyron Samaroo",
    "short_role": "software engineer · ML × systems · NYC",
    "handle": "tyron",
    "location": "NYC",
    "portfolio": "tyronsamaroo.dev",
    "email": "tyronsamaroo@gmail.com",
    "linkedin_path": "/in/tyronsamaroo",
    "linkedin_url": "https://www.linkedin.com/in/tyronsamaroo",
    "bio_short": "I build at the seam where ML meets systems — neural nets, compilers, things with zero dependencies. Based in NYC.",
    "mantra": "Ship it, then make it weird.",
    "rotating_taglines": [
        "I build things that teach machines.",
        "I write compilers for fun.",
        "I scraped Etsy with zero dependencies.",
        "Ship it. Then make it weird.",
    ],
    "boot_lines": [
        "[ OK ] mounting /dev/caffeine on /root/brain",
        "[ OK ] loading kernel module: make_it_weird.ko",
        "[ OK ] starting service: ship-it.service",
        "[WARN] toaster.sys not trusted — continuing anyway",
        "[ OK ] welcome back, tyron.",
    ],
    "skillicons_slug": "py,java,js,ts,react,nodejs,flask,tensorflow,pytorch,postgres,docker,git,linux",
    # Primary stack = what I'm using daily. Everything else = proven in shipped work.
    "primary_stack": [
        {"name": "Python",     "color": "3776AB", "logo": "python",     "text": "white"},
        {"name": "TypeScript", "color": "3178C6", "logo": "typescript", "text": "white"},
        {"name": "React",      "color": "61DAFB", "logo": "react",      "text": "20232A"},
        {"name": "uv",         "color": "DE5FE9", "logo": "uv",         "text": "white"},
        {"name": "shadcn/ui",  "color": "000000", "logo": "shadcnui",   "text": "white"},
    ],
    "stack": [
        # headline first so they sort to the front of every variation
        {"name": "Python",     "color": "3776AB", "logo": "python",     "text": "white"},
        {"name": "TypeScript", "color": "3178C6", "logo": "typescript", "text": "white"},
        {"name": "React",      "color": "61DAFB", "logo": "react",      "text": "20232A"},
        {"name": "uv",         "color": "DE5FE9", "logo": "uv",         "text": "white"},
        {"name": "shadcn/ui",  "color": "000000", "logo": "shadcnui",   "text": "white"},
        # rest — brand-native colors, each pops differently
        {"name": "Node.js",    "color": "339933", "logo": "node.js",    "text": "white"},
        {"name": "TensorFlow", "color": "FF6F00", "logo": "tensorflow", "text": "white"},
        {"name": "PyTorch",    "color": "EE4C2C", "logo": "pytorch",    "text": "white"},
        {"name": "Flask",      "color": "000000", "logo": "flask",      "text": "white"},
        {"name": "Java",       "color": "ED8B00", "logo": "openjdk",    "text": "white"},
        {"name": "PostgreSQL", "color": "4169E1", "logo": "postgresql", "text": "white"},
        {"name": "Docker",     "color": "2496ED", "logo": "docker",     "text": "white"},
        {"name": "Linux",      "color": "FCC624", "logo": "linux",      "text": "black"},
        {"name": "Git",        "color": "F05032", "logo": "git",        "text": "white"},
    ],
    "projects": [
        {"name": "ASL-Alpha-NeuralNet", "url": "https://github.com/TyronSamaroo/ASL-Alpha-NeuralNet",
         "emoji": "🧏", "tags": ["Python", "TensorFlow", "CV"],
         "short": "CNN that reads American Sign Language letters from a webcam. Accessibility + vision.",
         "insight": "data curation beat every architecture change I tried"},
        {"name": "Compiler-TinyJ", "url": "https://github.com/TyronSamaroo/Compiler-TinyJ",
         "emoji": "⚙️", "tags": ["Java", "Compilers"],
         "short": "A tiny Java compiler. Lexer → parser → codegen, end to end. From scratch.",
         "insight": "parser is boring; codegen is where you learn how computers work"},
        {"name": "Palate", "url": "https://github.com/TyronSamaroo/Palate",
         "emoji": "🍽️", "tags": ["React", "Node", "JS"],
         "short": "Full-stack React app for food discovery. Team project.",
         "insight": "modeling taste as latent preference beats explicit tags"},
        {"name": "EtsyScraper", "url": "https://github.com/TyronSamaroo/EtsyScraper",
         "emoji": "🧵", "tags": ["Java", "HTTP", "Parsing"],
         "short": "Web scraper built with only the Java JDK. No third-party libs. Pure grit.",
         "insight": "constraint-driven projects are the fastest way to understand a stack"},
        {"name": "SearchEngine", "url": "https://github.com/TyronSamaroo/SearchEngine",
         "emoji": "🔍", "tags": ["JavaScript", "IR"],
         "short": "Tiny search engine: indexing, ranking, query parser.",
         "insight": "classical ranking still beats cosine similarity for explainability"},
        {"name": "Stock_App_Flask", "url": "https://github.com/TyronSamaroo/Stock_App_Flask",
         "emoji": "📈", "tags": ["Python", "Flask", "APIs"],
         "short": "Flask stock tracker + portfolio views. Market data + caching.",
         "insight": "90% of the work ended up in the caching layer, not the app"},
    ],
    "now_lines": [
        "shipping at the intersection of ML × systems × product",
        "sharpening distributed systems + LLM infra",
        "open to collabs on anything with a compiler, a model, or a very strange idea",
        "best way in: tyronsamaroo@gmail.com",
    ],
    "quote": "wrote a compiler before I trusted myself with a toaster.",
}
