# Single source of truth for all README variations.
# Edit me, run `python3 build.py`, commit.

CONTENT = {
    "name": "Tyron Samaroo",
    "short_role": "software engineer · ML × systems · NYC",
    "handle": "tyron",
    "location": "NYC",
    "portfolio": "tyronsamaroo.dev",
    "email": "tyronsamaroo@gmail.com",
    "linkedin_path": "/in/tyronsamaroo",
    "linkedin_url": "https://www.linkedin.com/in/tyronsamaroo",
    "bio_short": "I build at the seam where ML meets systems — neural nets, compilers, things with zero dependencies. Based in NYC.",
    "mantra": "Ship it, then make it weird.",
    "rotating_taglines": [
        "I build things that teach machines.",
        "I write compilers for fun.",
        "I scraped Etsy with zero dependencies.",
        "Ship it. Then make it weird.",
    ],
    "boot_lines": [
        "[ OK ] mounting /dev/caffeine on /root/brain",
        "[ OK ] loading kernel module: make_it_weird.ko",
        "[ OK ] starting service: ship-it.service",
        "[WARN] toaster.sys not trusted — continuing anyway",
        "[ OK ] welcome back, tyron.",
    ],
    "skillicons_slug": "py,java,js,ts,react,nodejs,flask,tensorflow,pytorch,postgres,docker,git,linux",
    # Primary stack = what I'm using daily. Everything else = proven in shipped work.
    "primary_stack": [
        {"name": "Python",     "color": "3776AB", "logo": "python",     "text": "white"},
        {"name": "TypeScript", "color": "3178C6", "logo": "typescript", "text": "white"},
        {"name": "React",      "color": "61DAFB", "logo": "react",      "text": "20232A"},
        {"name": "uv",         "color": "DE5FE9", "logo": "uv",         "text": "white"},
        {"name": "shadcn/ui",  "color": "000000", "logo": "shadcnui",   "text": "white"},
    ],
    "stack": [
        # headline first so they sort to the front of every variation
        {"name": "Python",     "color": "3776AB", "logo": "python",     "text": "white"},
        {"name": "TypeScript", "color": "3178C6", "logo": "typescript", "text": "white"},
        {"name": "React",      "color": "61DAFB", "logo": "react",      "text": "20232A"},
        {"name": "uv",         "color": "DE5FE9", "logo": "uv",         "text": "white"},
        {"name": "shadcn/ui",  "color": "000000", "logo": "shadcnui",   "text": "white"},
        # rest — brand-native colors, each pops differently
        {"name": "Node.js",    "color": "339933", "logo": "node.js",    "text": "white"},
        {"name": "TensorFlow", "color": "FF6F00", "logo": "tensorflow", "text": "white"},
        {"name": "PyTorch",    "color": "EE4C2C", "logo": "pytorch",    "text": "white"},
        {"name": "Flask",      "color": "000000", "logo": "flask",      "text": "white"},
        {"name": "Java",       "color": "ED8B00", "logo": "openjdk",    "text": "white"},
        {"name": "PostgreSQL", "color": "4169E1", "logo": "postgresql", "text": "white"},
        {"name": "Docker",     "color": "2496ED", "logo": "docker",     "text": "white"},
        {"name": "Linux",      "color": "FCC624", "logo": "linux",      "text": "black"},
        {"name": "Git",        "color": "F05032", "logo": "git",        "text": "white"},
    ],
    "projects": [
        {"name": "dev-dashboard", "url": "https://github.com/TyronSamaroo/dev-dashboard",
         "emoji": "🖥️", "tags": ["TypeScript", "React", "Tailwind"],
         "short": "The site you're on — tyronsamaroo.dev. A portfolio shaped as a live dev dashboard (online/uptime status, ⌘K palette, sticky nav).",
         "insight": "treating a portfolio like a product makes it easier to keep alive"},
        {"name": "lollens", "url": "https://github.com/TyronSamaroo/lollens",
         "emoji": "🎮", "tags": ["TypeScript", "Electron", "macOS"],
         "short": "Native macOS overlay for League of Legends — live gold, stats, and augment tier list while you play.",
         "insight": "reading a running game's state is mostly systems work, not UI"},
        {"name": "daily-command-center", "url": "https://github.com/TyronSamaroo/daily-command-center",
         "emoji": "🧭", "tags": ["TypeScript", "React", "Vercel"],
         "short": "Unified daily dashboard — work blocks, contest prep, household coordination. Deployed.",
         "insight": "productivity tools die when capture friction exceeds the value of tracking"},
        {"name": "tyron-experiments", "url": "https://github.com/TyronSamaroo/tyron-experiments",
         "emoji": "🧪", "tags": ["Python", "uv", "FastAPI"],
         "short": "Monorepo of small Python experiments on uv — habit-hub, macro-tracker, workout-api, pomodoro-cli, coding-dashboard.",
         "insight": "uv makes Python projects cheap enough to be disposable"},
        {"name": "Compiler-TinyJ", "url": "https://github.com/TyronSamaroo/Compiler-TinyJ",
         "emoji": "⚙️", "tags": ["Java", "Compilers"],
         "short": "A tiny Java compiler. Lexer → parser → codegen, end to end. From scratch.",
         "insight": "parser is boring; codegen is where you learn how computers work"},
        {"name": "reader3", "url": "https://github.com/TyronSamaroo/reader3",
         "emoji": "📚", "tags": ["Python", "LLMs"],
         "short": "Read books together with LLMs. Chapter in, question out — surprisingly useful.",
         "insight": "the best LLM UX is still 'paste the whole thing, then ask'"},
    ],
    "now_lines": [
        "shipping at the intersection of ML × systems × product",
        "sharpening distributed systems + LLM infra",
        "open to collabs on anything with a compiler, a model, or a very strange idea",
        "best way in: tyronsamaroo@gmail.com",
    ],
    "quote": "wrote a compiler before I trusted myself with a toaster.",
}
